- name: "Create temporary build directory"
  ansible.builtin.tempfile:
    state: directory
  register: build_dir_temp

- name: "Downloading go"
  ansible.builtin.shell: |
    VERSION=$(curl -s https://go.dev/dl/?mode=json | jq -r '.[0].version')
    wget https://go.dev/dl/$VERSION.linux-amd64.tar.gz -O {{ build_dir_temp.path }}/go.linux-amd64.tar.gz

- name: "Checking for previous go installation"
  ansible.builtin.stat:
    path: "/usr/local/go"
  register: go_install_check
  become: true

- name: "Removing previous go installation"
  ansible.builtin.file:
    path: "/usr/local/go"
    state: absent
  when: go_install_check.stat.exists

- name: "Installing go"
  ansible.builtin.shell: |
    tar -C /usr/local -xzf {{ build_dir_temp.path }}/go.linux-amd64.tar.gz
  become: true

- name: "Adding go to path"
  ansible.builtin.shell: |
    export PATH=$PATH:/usr/local/go/bin

- name: "Cleaning up build directory"
  ansible.builtin.file:
    path: "{{ build_dir_temp.path }}"
    state: absent