---
- name: "Installing tools from apt"
  include_tasks: "apt.yml"

- name: "Installing golang"
  include_tasks: "golang.yml"

- name: "Installing Node.js and NPM"
  include_tasks: "node.yml"

- name: "Installing docker"
  include_tasks: "docker.yml"

- name: "Installing NVChad"
  include_tasks: "nvchad.yml"

- name: "Installing rust"
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
