- name: "Installing fnm"
  ansible.builtin.shell: |
    curl -o- https://fnm.vercel.app/install | bash

- name: "Setting up fnm environment and installing node"
  ansible.builtin.shell: |
    export FNM_PATH="/home/{{ ansible_user_id }}/.local/share/fnm"
    if [ -d "$FNM_PATH" ]; then
      export PATH="/home/{{ ansible_user_id }}/.local/share/fnm:$PATH"
      eval "`fnm env`"
      fnm install --latest
    fi

- name: "Installing node"
  ansible.builtin.shell: |
    /home/{{ ansible_user_id }}/.local/share/fnm/fnm install --latest