- name: "Installing fnm"
  ansible.builtin.shell: |
    curl -o- https://fnm.vercel.app/install | bash

- name: "Adding fnm to path"
  ansible.builtin.shell: |
    FNM_PATH="/home/{{ ansible_user_id }}/.local/share/fnm"
    if [ -d "$FNM_PATH" ]; then
      export PATH="/home/ubuntu-ansible/.local/share/fnm:$PATH"
      eval "`fnm env`"
    fi
  become: true

- name: "Installing node"
  ansible.builtin.shell: |
    fnm install --latest