---
- name: "Building Ubuntu"
  hosts: localhost
  connection: local

  roles:
    - role: "update-system"
    - role: "clone-dotfiles"
    - role: "configure-terminal"
    - role: "install-tools"

  tasks:
    - name: "Cleaning up dotfiles directory"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/dotfiles"
        state: absent
